### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [fabervae/music_library_mobile_syncer#1]
Greetings @fabervae  ,

I was passing by (this repository) and tought I'd like to collaborate by proposing a logo
if that's something that may interest you! let me know!

I'm a Graphic Designer and an Open Source enthusiastic
looking to improve my portfolio and collaborate to really cool projects like this one!

Best Regards,
-Luigi.

**Comment by budget-coder** [comment]
Hi @LuigiBaute ,
Sorry for the late reply; an exam was consuming 99 % of my energy. I have never even thought of adding a logo to this project (mostly because I have zero skills in graphics design), so your idea sounds really cool!
Would it come at a price (which is fair), or is it free? If it is the former, then I can't be of much help with improving your portfolio.
